language: python
dist: xenial
python:
  - 3.7

env:
  global:
  - TRAVIS_RUST_VERSION=stable
  - RUST_BACKTRACE=1
  - TWINE_USERNAME = ${{ secrets.PYPI_USERNAME }}
  - TWINE_PASSWORD =  ${{ secrets.PYPI_PASSWORD }} 
jobs:
  include:
    - stage: deploy
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.6
            - python3.7
            - python3.8
      before_install:
        - source /ci/setup_rust.sh
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py sdist bdist_wheel && twine upload dist/* 